### ISSUE TITLE
MemoTooLongException

### ISSUE THREAD

**Issue by OttoVT** [elucidsoft/dotnet-stellar-sdk#280] opened 2020-10-13 14:12 UTC
**Describe the bug**
When trying to get a memo of a transaction in prod with a hash which equals to "63f4f14bd1c6cd4efeb677e412b618d49527e42cb2bdb3db9bb458b6485f7bf2", I receive an Exception:

stellar_dotnet_sdk.MemoTooLongException: 'text must be <= 28 bytes. length=38'
   at stellar_dotnet_sdk.MemoText..ctor(String text)
   at stellar_dotnet_sdk.Memo.Text(String text)
   at stellar_dotnet_sdk.responses.TransactionResponse.get_Memo()

Here is the link in explorer:
(https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjYzZjRmMTRiZDFjNmNkNGVmZWI2NzdlNDEyYjYxOGQ0OTUyN2U0MmNiMmJkYjNkYjliYjQ1OGI2NDg1ZjdiZjIifQ%3D%3D&network=public)

**To Reproduce**
1) Execute the next code:
stellar-dotnet-sdk version 5.0.36

var server = new Server("https://horizon.stellar.org");
var transactions = await server.Transactions.ForLedger(blockNumber)
                .IncludeFailed(true)
                .Limit(_limit)
                .Execute();

var memoXdr = transactions[25].Memo.ToXdr(); //Expecte the exception here

**Expected behavior**
Well, the thing is that memo for this particular transaction is "�\"<r~=Zp\u0016���8��y��i�".
Also, this transaction has a field "successful": true. I guess this is a bug in Stellar Protocol. ??)
The expected behavior is not to have such an exception. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14955144/95872109-81864480-0d7f-11eb-99fd-76158a190548.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 2004 (Build 1904ю508)

**Additional context**
stellar-dotnet-sdk version 5.0.36

**Comment by Kirbyrawr** [comment] 2020-10-14 15:41
Hi, checking now!

**Comment by Kirbyrawr** [comment] 2020-10-14 15:59
I think you are right it sounds like a bug in the protocol, i will talk to the team, thanks for the heads up

**Comment by Kirbyrawr** [comment] 2020-10-14 16:05
Forget my last comment, talked to other maintainer and we found that we are decoding it wrongly, i will keep you updated.

**Comment by Kirbyrawr** [comment] 2020-10-14 16:21
Hi, i uploaded a branch already to fix this issue, my teammate should look into it to verify is the way to proceed in this case.

Thanks for the report!

https://github.com/elucidsoft/dotnet-stellar-sdk/tree/memo-length-fix

**Comment by OttoVT** [comment] 2020-10-14 16:31
You are welcome ).
Thanks for the quick fix!

**Comment by elucidsoft** [comment] 2020-10-31 15:45
Sorry for the delay, we will be fixing and merging these changes shortly.

**Comment by Kirbyrawr** [comment] 2020-11-09 19:26
Hi, the issue is fixed, waiting for a release but it-s merged already since days ago, sorry for the confusion.

**Comment by elucidsoft** [comment] 2020-11-12 02:12
This will go into the 6.0 Release

**Closed by elucidsoft** 2020-11-12 02:12 UTC
