### ISSUE TITLE
Gateway timeout 504 does not get reported by any response code. 

### ISSUE THREAD

**Issue by HarvieKrumpet** [elucidsoft/dotnet-stellar-sdk#363] opened 2022-05-23 21:42 UTC
A 504 error is only returned as a null result. Any message returned by the Stellar api is lost. 

This message is actually being sent by the Server but not kept by the response.

Your request timed out before completing.  Please try your request again. If you are submitting a transaction make sure you are sending exactly the same transaction (with the same sequence number).

**Comment by elucidsoft** [comment] 2022-05-25 13:04
We will take a look.

**Comment by Kirbyrawr** [comment] 2022-05-30 22:23
Can you please provide more info, steps to reproduce the error, etc..? It help us to pinpoint the issue, thanks.

**Comment by elucidsoft** [comment] 2022-06-10 13:13
@HarvieKrumpet

**Comment by elucidsoft** [comment] 2022-11-24 01:06
Can't reproduce. Closing issue!

**Closed by elucidsoft** 2022-11-24 01:06 UTC
Labels: bug
